micronaut:
  application:
    name: micronaut-microservice-demo
  server:
    host: localhost
    port: 8081

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/demo
    driverClassName: org.postgresql.Driver
    username: root
    password: root

jpa:
  default:
    packages-to-scan:
      - 'com.rednavis.micronaut.employee'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      locations: classpath:db/migration